# Generated by Django 3.2.6 on 2022-03-01 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorbestellenapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_code', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=20, unique=True)),
                ('room_type', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=20)),
                ('room_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorbestellenapp.users', to_field='username')),
            ],
        ),
    ]
