# Generated by Django 3.2.6 on 2022-03-13 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorbestellenapp', '0005_auto_20220313_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='room_code',
        ),
        migrations.AddField(
            model_name='reservations',
            name='room_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vorbestellenapp.rooms', to_field='room_name'),
            preserve_default=False,
        ),
    ]
