# Generated by Django 3.2.6 on 2022-03-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorbestellenapp', '0006_auto_20220313_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservations',
            name='full_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
