# Generated by Django 3.2.6 on 2022-03-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorbestellenapp', '0007_auto_20220313_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='address',
        ),
        migrations.AddField(
            model_name='reservations',
            name='contact',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
