# Generated by Django 3.2.6 on 2022-03-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vorbestellenapp', '0008_auto_20220313_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='full_name',
        ),
    ]
