# Generated by Django 3.2.6 on 2022-03-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorbestellenapp', '0009_remove_reservations_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='payment',
            field=models.FloatField(default=10.0),
            preserve_default=False,
        ),
    ]
